### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [foucist/yo_tag#1]
Dear James,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by sergeevabc** [comment]
Is there anything a mere user like me could do to expedite a resolution of this issue?

**Comment by foucist** [comment]
Thanks for the interest but tagmv isn't quite ready to be widely used, it's got a major bug that I need to fix.  Need to replace the existing regular expression matching stuff with a proper parser. 

I've paused on this project so I don't know when I'll get around to making the changes, then I could look at compiling the ruby to an .exe after.

**Comment by sergeevabc** [comment]
Thank you for letting me know, James.
